### ISSUE TITLE
Ad-Blocking DNS from NordVPN?

### ISSUE THREAD

**Issue by mxwmnn** [mustafachyi/NordVPN-WireGuard-Config-Generator#3]
Would be awesome to have the option to an ad blocking dns? Or how does NordVPN manage their Adblocking feature?

**Comment by mustafachyi** [comment]
so you want an option for selecting the dns is that what you mean ?

**Comment by mxwmnn** [comment]
Yes, i know how to change the DNS in the configs even automated. But the AdBlocking DNS is in Germany so if i want to appear from another country this would result in dns leakage . But i couldn't find the ad blocking DNS Servers from NordVPN? Do they have one?

**Comment by mustafachyi** [comment]
Well i did a quick search and tested a few configs using the dns from "https://nextdns.io/" that seems to be working well further testing is needed ofc i will be glad to hear from you again !

**Comment by mxwmnn** [comment]
I had a own wireguard server setup, and i use the DNS from https://dnsforge.de/

They have ad blocking dns, that fits well. But i thought that maybe NordVPN has special ad blocking DNS Servers, but seems not so if you couldn't find anything about it. 
Another VPN Provider has this. They have a special internal DNS Server with DNS Blocking. But good with only changing to a open DNS server i can do it on my own. 

Thanks.
