### ISSUE TITLE
Fetch all wireguard servers

### ISSUE THREAD

**Issue by Pharaoh2k** [mustafachyi/NordVPN-WireGuard-Config-Generator#4]
Hi,

Thank you for this project! Nice work!

I am trying to fetch all wireguard servers in a specific city (London in this case), however the executable (nordvpn-wireguard-config-generator.exe) only fetches a single server per city and sadly that specific server doesn't work, tho does connet. Others do work, but not the London WG server.
Could you please add a feature to fetch all servers and/or specific server by id, like United Kingdom #2254 etc.?

Thanks again!

**Comment by mustafachyi** [comment]
I think you are talking about the best configs folder which indeed shows only one server per city but you could still check the other folder named "configs" and go to the country/city folder {United_Kingdom\London} in your case you should find all configs there and you could always use the web version i think it much easier to use for most users. Let me know if you have other comments about this

**Comment by Pharaoh2k** [comment]
Oh boy, I don't know how I missed that second folder....I guess ageing can do that to you lol
Thank you very much, that solved my problem.
I don't know how it picks the best configs, but as I mentioned, the London config it picked doesn't work at all. Other London configs from the `/configs` folder work perfectly fine. :)
