### ISSUE TITLE
Web version: Not only Download, add text box and Barcode

### ISSUE THREAD

**Issue by ewwink** [mustafachyi/NordVPN-WireGuard-Config-Generator#6]
PC/Mobile: It simpler to copy paste than download
Mobile: Scan to add the config
Add text form for private key, with notice the private key will not recoded/uploaded. input once than any config already with the user private key.

**Comment by mustafachyi** [comment]
Sure, I’ll get started on this! I can also add the private key text option as an extra feature, just in case. Just to confirm, you want these updates in V2, right?

**Comment by ewwink** [comment]
yes V2, and thank you.

**Comment by mustafachyi** [comment]
Added the requested features! I left out the private key for security reasons and to avoid any suspicion. Hope it didn't take too long!
